on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

name: Release Drafter
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true




permissions:
  contents: read

jobs:
  release-drafter:
    uses: KooshaPari/phenoShared/.github/workflows/reusable-release-drafter.yml@438e2e71e448c9f1f47f184d3ca4acbb28928677
    permissions:
      contents: write
      pull-requests: write
