name: TruffleHog Secrets Scan
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


permissions:
  contents: read

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@d411fff7b8879a62509f3fa98c07f247ac089a51
        with:
          path: ./
          base_depth: 1
          debug: true
